import type { Specialty } from "./types";

// Compact specialty database. Trait values are 0..1 (ideal profile).
// Only meaningful traits per specialty are listed; missing traits are treated as neutral.

export const SPECIALTIES: Specialty[] = [
  {
    id: "dermatology",
    name: "Dermatology",
    blurb: "Visual diagnosis, predictable rhythm, procedural variety, mostly outpatient.",
    trainingYears: "4 yrs residency",
    incomeBand: 5, competitiveness: 5, lifestyle: 5, burnoutRisk: 2,
    emotionalBurden: 2, procedural: 4, patientInteraction: 4, callBurden: 1,
    emergencyFrequency: 1, physicalDemand: 2, familyFriendly: 5, autonomy: 5, prestige: 4,
    ideal: { visual_spatial: 0.8, perfectionism: 0.7, routine_preference: 0.7, lifestyle_balance: 0.9, family_priority: 0.8, income_priority: 0.8, specialized_vs_broad: 0.8, chronic_vs_acute: 0.2, death_comfort: 0.3, emotional_resilience: 0.5 },
    thrives: ["Visual pattern recognition", "High-volume outpatient flow", "Mix of cognitive + minor procedures"],
    struggles: ["Need for adrenaline / emergencies", "Wanting to feel heroic in life-or-death moments"],
    downsides: ["Cosmetic pressure", "Repetitive cases", "Hyper-competitive match"],
    dayInLife: "Clinic 8–5, 30–50 patients, biopsies between rooms, charts done by 6pm.",
    tags: ["lifestyle", "visual", "outpatient"],
  },
  {
    id: "psychiatry",
    name: "Psychiatry",
    blurb: "Deep human conversation, longitudinal care, the inner life as the patient.",
    trainingYears: "4 yrs residency",
    incomeBand: 3, competitiveness: 2, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 4, procedural: 1, patientInteraction: 5, callBurden: 2,
    emergencyFrequency: 2, physicalDemand: 1, familyFriendly: 5, autonomy: 5, prestige: 3,
    ideal: { empathy: 0.9, patience: 0.9, uncertainty_tolerance: 0.8, communication: 0.9, sensitivity: 0.7, lifestyle_balance: 0.7, chronic_vs_acute: 0.2, analytical: 0.6, autonomy: 0.8, ethical_burden_tolerance: 0.7, procedural: 0.1 },
    thrives: ["Long, nuanced conversations", "Tolerating ambiguity and slow change", "Boundary-setting"],
    struggles: ["Wanting fast, visible results", "Discomfort with sustained emotional weight"],
    downsides: ["Stigma", "Slow patient progress", "Vicarious trauma"],
    dayInLife: "6–8 patients, 30–60 min each, careful notes, evenings protected.",
    tags: ["cognitive", "lifestyle", "longitudinal"],
  },
  {
    id: "neurosurgery",
    name: "Neurosurgery",
    blurb: "High-stakes precision, brutal training, identity-defining career.",
    trainingYears: "7 yrs residency",
    incomeBand: 5, competitiveness: 5, lifestyle: 1, burnoutRisk: 5,
    emotionalBurden: 5, procedural: 5, patientInteraction: 3, callBurden: 5,
    emergencyFrequency: 5, physicalDemand: 5, familyFriendly: 1, autonomy: 4, prestige: 5,
    ideal: { stamina: 1.0, perfectionism: 1.0, identity_career: 1.0, competitiveness: 0.9, procedural: 1.0, visual_spatial: 0.95, emotional_resilience: 0.95, ambition: 0.95, prestige_motivation: 0.8, delayed_gratification: 0.95, death_comfort: 0.9, lifestyle_balance: 0.1, family_priority: 0.2, focus_style: 0.3 },
    thrives: ["Long procedures requiring obsessive precision", "Identity fused with craft"],
    struggles: ["Need for predictable hours", "Limited tolerance for adverse outcomes"],
    downsides: ["7+ years training", "Severe burnout rates", "Family strain"],
    dayInLife: "5am rounds, 8–14h OR days, in-house call several nights/month.",
    tags: ["procedural", "surgical", "high-acuity"],
  },
  {
    id: "cardiac_surgery",
    name: "Cardiac Surgery",
    blurb: "Open-heart precision, long training, life-and-death routine.",
    trainingYears: "6–8 yrs",
    incomeBand: 5, competitiveness: 5, lifestyle: 1, burnoutRisk: 5,
    emotionalBurden: 5, procedural: 5, patientInteraction: 3, callBurden: 5,
    emergencyFrequency: 4, physicalDemand: 5, familyFriendly: 1, autonomy: 4, prestige: 5,
    ideal: { stamina: 1.0, perfectionism: 1.0, procedural: 1.0, visual_spatial: 0.9, emotional_resilience: 0.95, competitiveness: 0.9, identity_career: 0.95, delayed_gratification: 0.95, death_comfort: 0.95, lifestyle_balance: 0.1, family_priority: 0.2 },
    thrives: ["Sustained focus over hours", "High personal stakes"],
    struggles: ["Need for balance", "Aversion to mortality conversations"],
    downsides: ["Brutal hours", "Declining case volume in some regions"],
    dayInLife: "Pre-op 5:30am, OR till evening, ICU rounds late.",
    tags: ["procedural", "surgical", "high-acuity"],
  },
  {
    id: "emergency_medicine",
    name: "Emergency Medicine",
    blurb: "Acute chaos, shift work, undifferentiated patients all day.",
    trainingYears: "3–4 yrs",
    incomeBand: 4, competitiveness: 3, lifestyle: 3, burnoutRisk: 5,
    emotionalBurden: 5, procedural: 4, patientInteraction: 4, callBurden: 2,
    emergencyFrequency: 5, physicalDemand: 4, familyFriendly: 3, autonomy: 4, prestige: 3,
    ideal: { risk_tolerance: 0.9, focus_style: 0.95, stamina: 0.8, uncertainty_tolerance: 0.95, communication: 0.8, emotional_resilience: 0.9, death_comfort: 0.9, chronic_vs_acute: 1.0, specialized_vs_broad: 0.1, social_battery: 0.7, routine_preference: 0.2 },
    thrives: ["Rapid task-switching", "Comfort with chaos and unknowns", "Procedural variety"],
    struggles: ["Need for long-term patient relationships", "Sensitivity to shift work / circadian disruption"],
    downsides: ["Night shifts", "Compassion fatigue", "Volume pressure"],
    dayInLife: "12-hour shifts, 20+ patients, constant interruptions, no follow-up.",
    tags: ["acute", "shift-work", "broad"],
  },
  {
    id: "internal_medicine",
    name: "Internal Medicine",
    blurb: "Complex multi-system reasoning. Foundation for many subspecialties.",
    trainingYears: "3 yrs",
    incomeBand: 3, competitiveness: 2, lifestyle: 3, burnoutRisk: 4,
    emotionalBurden: 3, procedural: 2, patientInteraction: 4, callBurden: 3,
    emergencyFrequency: 3, physicalDemand: 2, familyFriendly: 3, autonomy: 3, prestige: 3,
    ideal: { analytical: 0.9, patience: 0.7, communication: 0.7, specialized_vs_broad: 0.3, uncertainty_tolerance: 0.7, chronic_vs_acute: 0.4, lifestyle_balance: 0.5 },
    thrives: ["Diagnostic puzzles", "Team-based care"],
    struggles: ["Procedural-focused minds", "Need for fast closure"],
    downsides: ["Documentation burden", "Lower pay vs subspecialty"],
    dayInLife: "Rounds, notes, admissions, discharge planning, repeat.",
    tags: ["cognitive", "broad"],
  },
  {
    id: "family_medicine",
    name: "Family Medicine",
    blurb: "Cradle-to-grave continuity, broad scope, community-rooted.",
    trainingYears: "3 yrs",
    incomeBand: 2, competitiveness: 1, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 3, procedural: 2, patientInteraction: 5, callBurden: 2,
    emergencyFrequency: 2, physicalDemand: 2, familyFriendly: 5, autonomy: 4, prestige: 2,
    ideal: { empathy: 0.9, communication: 0.9, patience: 0.8, specialized_vs_broad: 0.2, chronic_vs_acute: 0.2, lifestyle_balance: 0.8, family_priority: 0.8, prestige_motivation: 0.2, income_priority: 0.3 },
    thrives: ["Long relationships", "Community work", "Broad knowledge"],
    struggles: ["Status-seeking", "Procedural-focused minds"],
    downsides: ["Lower pay", "Volume pressure in primary care"],
    dayInLife: "20–30 patients/day, 15-min visits, charting evenings.",
    tags: ["broad", "lifestyle", "longitudinal"],
  },
  {
    id: "anesthesiology",
    name: "Anesthesiology",
    blurb: "Physiologic vigilance, procedural, controlled environment.",
    trainingYears: "4 yrs",
    incomeBand: 5, competitiveness: 3, lifestyle: 3, burnoutRisk: 3,
    emotionalBurden: 3, procedural: 4, patientInteraction: 2, callBurden: 3,
    emergencyFrequency: 3, physicalDemand: 2, familyFriendly: 3, autonomy: 4, prestige: 4,
    ideal: { focus_style: 0.4, perfectionism: 0.85, procedural: 0.8, analytical: 0.8, social_battery: 0.4, communication: 0.5, emotional_resilience: 0.8, income_priority: 0.7 },
    thrives: ["Calm under physiologic chaos", "Procedural craft without long clinic"],
    struggles: ["Need for deep patient relationships"],
    downsides: ["Vigilance fatigue", "Call burden"],
    dayInLife: "Cases back to back, monitor, induce, emerge, repeat.",
    tags: ["procedural", "perioperative"],
  },
  {
    id: "orthopedics",
    name: "Orthopedics",
    blurb: "Mechanical, athletic, restorative procedures.",
    trainingYears: "5 yrs",
    incomeBand: 5, competitiveness: 5, lifestyle: 3, burnoutRisk: 3,
    emotionalBurden: 2, procedural: 5, patientInteraction: 3, callBurden: 4,
    emergencyFrequency: 3, physicalDemand: 5, familyFriendly: 2, autonomy: 4, prestige: 4,
    ideal: { stamina: 0.9, procedural: 1.0, visual_spatial: 0.9, competitiveness: 0.9, ambition: 0.8, income_priority: 0.9, prestige_motivation: 0.7, lifestyle_balance: 0.3 },
    thrives: ["Physical craft", "Clear mechanical fixes"],
    struggles: ["Aversion to physical work", "Wanting cerebral cases"],
    downsides: ["Physically demanding", "Call burden early career"],
    dayInLife: "OR most days, clinic 1–2 days, trauma call.",
    tags: ["procedural", "surgical"],
  },
  {
    id: "ophthalmology",
    name: "Ophthalmology",
    blurb: "Microsurgery, restorative, lifestyle-friendly.",
    trainingYears: "4 yrs",
    incomeBand: 5, competitiveness: 5, lifestyle: 5, burnoutRisk: 2,
    emotionalBurden: 2, procedural: 5, patientInteraction: 3, callBurden: 2,
    emergencyFrequency: 1, physicalDemand: 2, familyFriendly: 5, autonomy: 5, prestige: 4,
    ideal: { visual_spatial: 0.95, perfectionism: 0.9, procedural: 0.9, lifestyle_balance: 0.9, family_priority: 0.8, income_priority: 0.8, focus_style: 0.3 },
    thrives: ["Microscopic precision", "Restoring sight"],
    struggles: ["Coarse motor preference"],
    downsides: ["Narrow scope", "Competitive match"],
    dayInLife: "Clinic mornings, OR afternoons, home by 6.",
    tags: ["procedural", "lifestyle"],
  },
  {
    id: "ent",
    name: "ENT (Otolaryngology)",
    blurb: "Head & neck surgery, varied cases, decent lifestyle.",
    trainingYears: "5 yrs",
    incomeBand: 5, competitiveness: 5, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 3, procedural: 5, patientInteraction: 3, callBurden: 3,
    emergencyFrequency: 2, physicalDemand: 3, familyFriendly: 4, autonomy: 4, prestige: 4,
    ideal: { procedural: 0.9, visual_spatial: 0.85, perfectionism: 0.8, lifestyle_balance: 0.7, income_priority: 0.8, ambition: 0.8 },
    thrives: ["Mix of clinic + complex surgery", "Anatomic detail"],
    struggles: ["Need for adrenaline", "Aversion to clinic"],
    downsides: ["H&N oncology emotional weight"],
    dayInLife: "Clinic + OR mix, 1–2 cases/day on operating days.",
    tags: ["procedural", "surgical"],
  },
  {
    id: "plastics",
    name: "Plastic Surgery",
    blurb: "Reconstructive + aesthetic craft, long training.",
    trainingYears: "6 yrs",
    incomeBand: 5, competitiveness: 5, lifestyle: 3, burnoutRisk: 3,
    emotionalBurden: 3, procedural: 5, patientInteraction: 4, callBurden: 3,
    emergencyFrequency: 2, physicalDemand: 3, familyFriendly: 3, autonomy: 5, prestige: 5,
    ideal: { perfectionism: 0.95, visual_spatial: 0.95, procedural: 1.0, ambition: 0.9, income_priority: 0.9, prestige_motivation: 0.85, autonomy: 0.9 },
    thrives: ["Aesthetic craftsmanship", "Building a private practice"],
    struggles: ["Aversion to entrepreneurship"],
    downsides: ["Litigation risk", "Cosmetic pressure"],
    dayInLife: "Mix of recon and cosmetic, OR-heavy.",
    tags: ["procedural", "surgical"],
  },
  {
    id: "pmr",
    name: "Physical Medicine & Rehab",
    blurb: "Function, mobility, recovery; team-based and cognitive.",
    trainingYears: "4 yrs",
    incomeBand: 3, competitiveness: 2, lifestyle: 5, burnoutRisk: 2,
    emotionalBurden: 3, procedural: 2, patientInteraction: 5, callBurden: 1,
    emergencyFrequency: 1, physicalDemand: 2, familyFriendly: 5, autonomy: 4, prestige: 2,
    ideal: { empathy: 0.8, communication: 0.8, patience: 0.85, lifestyle_balance: 0.9, family_priority: 0.8, chronic_vs_acute: 0.25 },
    thrives: ["Team rehab work", "Slow, measurable progress"],
    struggles: ["Need for acute action"],
    downsides: ["Lower pay vs procedural", "Slow visible change"],
    dayInLife: "Rounds, team meetings, outpatient injections, evenings free.",
    tags: ["lifestyle", "longitudinal"],
  },
  {
    id: "pathology",
    name: "Pathology",
    blurb: "Microscope, slides, diagnostic certainty without bedside.",
    trainingYears: "4 yrs",
    incomeBand: 4, competitiveness: 2, lifestyle: 5, burnoutRisk: 2,
    emotionalBurden: 2, procedural: 2, patientInteraction: 1, callBurden: 2,
    emergencyFrequency: 1, physicalDemand: 1, familyFriendly: 5, autonomy: 4, prestige: 3,
    ideal: { introversion: 0.85, analytical: 0.95, visual_spatial: 0.85, focus_style: 0.2, social_battery: 0.2, communication: 0.3, lifestyle_balance: 0.9, perfectionism: 0.85 },
    thrives: ["Deep solo focus", "Pattern recognition"],
    struggles: ["Need for patient contact", "Extroverts"],
    downsides: ["Isolation", "Image of being 'invisible'"],
    dayInLife: "Slides, sign-outs, tumor board, home by 5.",
    tags: ["cognitive", "non-clinical"],
  },
  {
    id: "diagnostic_radiology",
    name: "Diagnostic Radiology",
    blurb: "Image interpretation, pattern recognition, dark room flow state.",
    trainingYears: "5 yrs",
    incomeBand: 5, competitiveness: 4, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 2, procedural: 2, patientInteraction: 1, callBurden: 3,
    emergencyFrequency: 2, physicalDemand: 1, familyFriendly: 4, autonomy: 4, prestige: 4,
    ideal: { introversion: 0.8, visual_spatial: 0.95, analytical: 0.9, focus_style: 0.25, social_battery: 0.25, perfectionism: 0.85, income_priority: 0.8, lifestyle_balance: 0.7 },
    thrives: ["Solo concentration", "Visual reasoning at scale"],
    struggles: ["Need for relationships", "Discomfort with isolation"],
    downsides: ["AI disruption anxiety", "Volume pressure"],
    dayInLife: "Read 80–150 studies, dictate, brief consults.",
    tags: ["cognitive", "lifestyle"],
  },
  {
    id: "ir",
    name: "Interventional Radiology",
    blurb: "Image-guided procedures, minimally invasive cures.",
    trainingYears: "6 yrs",
    incomeBand: 5, competitiveness: 4, lifestyle: 3, burnoutRisk: 4,
    emotionalBurden: 3, procedural: 5, patientInteraction: 3, callBurden: 4,
    emergencyFrequency: 4, physicalDemand: 3, familyFriendly: 3, autonomy: 4, prestige: 4,
    ideal: { procedural: 0.95, visual_spatial: 0.9, analytical: 0.85, risk_tolerance: 0.7, ambition: 0.85, income_priority: 0.8 },
    thrives: ["Procedural elegance", "Tech-forward practice"],
    struggles: ["Aversion to call burden"],
    downsides: ["Heavy call", "Radiation exposure"],
    dayInLife: "Procedures + reading shifts, frequent emergencies.",
    tags: ["procedural", "tech"],
  },
  {
    id: "obgyn",
    name: "OB/GYN",
    blurb: "Surgery + primary care + delivery. Emotional spectrum from joy to loss.",
    trainingYears: "4 yrs",
    incomeBand: 4, competitiveness: 3, lifestyle: 2, burnoutRisk: 5,
    emotionalBurden: 4, procedural: 4, patientInteraction: 5, callBurden: 5,
    emergencyFrequency: 5, physicalDemand: 3, familyFriendly: 2, autonomy: 3, prestige: 3,
    ideal: { empathy: 0.85, stamina: 0.85, procedural: 0.7, communication: 0.85, emotional_resilience: 0.85, focus_style: 0.7 },
    thrives: ["Surgery + relationships", "Joy of delivery"],
    struggles: ["Sleep needs", "Litigation aversion"],
    downsides: ["Brutal call", "High litigation"],
    dayInLife: "Clinic + L&D + OR + night call.",
    tags: ["surgical", "high-acuity"],
  },
  {
    id: "general_surgery",
    name: "General Surgery",
    blurb: "Operative breadth, intense training, foundational craft.",
    trainingYears: "5 yrs",
    incomeBand: 4, competitiveness: 3, lifestyle: 2, burnoutRisk: 4,
    emotionalBurden: 4, procedural: 5, patientInteraction: 3, callBurden: 5,
    emergencyFrequency: 4, physicalDemand: 5, familyFriendly: 2, autonomy: 4, prestige: 4,
    ideal: { stamina: 0.95, procedural: 0.95, perfectionism: 0.85, competitiveness: 0.85, identity_career: 0.85, emotional_resilience: 0.85, lifestyle_balance: 0.25 },
    thrives: ["Operative craft", "High-stakes problem solving"],
    struggles: ["Need for sleep and family"],
    downsides: ["Long training", "Heavy call"],
    dayInLife: "OR mornings, clinic afternoons, call nights.",
    tags: ["surgical", "procedural"],
  },
  {
    id: "vascular_surgery",
    name: "Vascular Surgery",
    blurb: "Endovascular + open surgery, complex chronic disease.",
    trainingYears: "5–7 yrs",
    incomeBand: 5, competitiveness: 4, lifestyle: 2, burnoutRisk: 4,
    emotionalBurden: 4, procedural: 5, patientInteraction: 3, callBurden: 5,
    emergencyFrequency: 4, physicalDemand: 4, familyFriendly: 2, autonomy: 4, prestige: 4,
    ideal: { stamina: 0.9, procedural: 0.95, visual_spatial: 0.9, emotional_resilience: 0.85, identity_career: 0.85 },
    thrives: ["Hybrid OR work", "Long-term limb salvage"],
    struggles: ["Need for predictable nights"],
    downsides: ["High call", "Difficult patient population"],
    dayInLife: "Endo suite, OR, ICU rounds.",
    tags: ["surgical", "procedural"],
  },
  {
    id: "trauma_surgery",
    name: "Trauma / Acute Care Surgery",
    blurb: "Acute operative care, on-the-edge decisions.",
    trainingYears: "5+1 yrs",
    incomeBand: 4, competitiveness: 3, lifestyle: 1, burnoutRisk: 5,
    emotionalBurden: 5, procedural: 5, patientInteraction: 3, callBurden: 5,
    emergencyFrequency: 5, physicalDemand: 5, familyFriendly: 1, autonomy: 4, prestige: 4,
    ideal: { risk_tolerance: 0.95, stamina: 0.95, focus_style: 0.85, emotional_resilience: 0.95, death_comfort: 0.95, chronic_vs_acute: 1.0, lifestyle_balance: 0.1, family_priority: 0.2 },
    thrives: ["Adrenaline", "Decisive action under chaos"],
    struggles: ["Need for predictability"],
    downsides: ["Sleep destruction", "Vicarious trauma"],
    dayInLife: "Shift-based, OR + ICU + ED, nights frequent.",
    tags: ["acute", "surgical"],
  },
  {
    id: "pediatrics",
    name: "Pediatrics",
    blurb: "Children & families, preventive care, lifestyle-friendly outpatient.",
    trainingYears: "3 yrs",
    incomeBand: 2, competitiveness: 2, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 4, procedural: 1, patientInteraction: 5, callBurden: 2,
    emergencyFrequency: 2, physicalDemand: 2, familyFriendly: 5, autonomy: 3, prestige: 3,
    ideal: { empathy: 0.95, communication: 0.9, patience: 0.85, family_priority: 0.85, lifestyle_balance: 0.7, sensitivity: 0.6, income_priority: 0.2 },
    thrives: ["Playful warmth", "Family communication"],
    struggles: ["Need for high income", "Discomfort with parents"],
    downsides: ["Low pay vs adult fields", "Difficult cases hit hard"],
    dayInLife: "Well visits, sick visits, vaccines, parent calls.",
    tags: ["longitudinal", "lifestyle"],
  },
  {
    id: "neurology",
    name: "Neurology",
    blurb: "Pattern recognition of the nervous system; many incurable conditions.",
    trainingYears: "4 yrs",
    incomeBand: 3, competitiveness: 3, lifestyle: 3, burnoutRisk: 4,
    emotionalBurden: 4, procedural: 2, patientInteraction: 4, callBurden: 3,
    emergencyFrequency: 3, physicalDemand: 2, familyFriendly: 4, autonomy: 4, prestige: 3,
    ideal: { analytical: 0.95, patience: 0.85, uncertainty_tolerance: 0.8, communication: 0.7, ethical_burden_tolerance: 0.8 },
    thrives: ["Diagnostic localization", "Cognitive puzzles"],
    struggles: ["Need for cure-driven feedback"],
    downsides: ["Many untreatable diseases", "Stroke call"],
    dayInLife: "Clinic + EEG/EMG + consult service.",
    tags: ["cognitive"],
  },
  {
    id: "rheumatology",
    name: "Rheumatology",
    blurb: "Chronic autoimmune, deep cognitive workups.",
    trainingYears: "3+2 yrs",
    incomeBand: 3, competitiveness: 2, lifestyle: 5, burnoutRisk: 2,
    emotionalBurden: 3, procedural: 2, patientInteraction: 4, callBurden: 1,
    emergencyFrequency: 1, physicalDemand: 1, familyFriendly: 5, autonomy: 4, prestige: 3,
    ideal: { analytical: 0.9, patience: 0.9, uncertainty_tolerance: 0.85, lifestyle_balance: 0.9, family_priority: 0.8, chronic_vs_acute: 0.15 },
    thrives: ["Long workups, slow trust"],
    struggles: ["Need for procedural action"],
    downsides: ["Lower pay", "Limited cures"],
    dayInLife: "Outpatient clinic, infusions, lab review.",
    tags: ["cognitive", "lifestyle"],
  },
  {
    id: "endocrinology",
    name: "Endocrinology",
    blurb: "Hormones, labs, long-term chronic management.",
    trainingYears: "3+2 yrs",
    incomeBand: 2, competitiveness: 2, lifestyle: 5, burnoutRisk: 2,
    emotionalBurden: 2, procedural: 1, patientInteraction: 4, callBurden: 1,
    emergencyFrequency: 1, physicalDemand: 1, familyFriendly: 5, autonomy: 4, prestige: 3,
    ideal: { analytical: 0.85, patience: 0.9, lifestyle_balance: 0.9, family_priority: 0.85, chronic_vs_acute: 0.15, income_priority: 0.3 },
    thrives: ["Lab-driven adjustments", "Stable schedule"],
    struggles: ["Need for procedural variety"],
    downsides: ["Low pay vs IM peers"],
    dayInLife: "Outpatient, diabetes counseling, thyroid workups.",
    tags: ["cognitive", "lifestyle"],
  },
  {
    id: "infectious_disease",
    name: "Infectious Disease",
    blurb: "Detective work in inpatient & outpatient settings.",
    trainingYears: "3+2 yrs",
    incomeBand: 2, competitiveness: 2, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 3, procedural: 1, patientInteraction: 3, callBurden: 2,
    emergencyFrequency: 2, physicalDemand: 1, familyFriendly: 4, autonomy: 4, prestige: 3,
    ideal: { analytical: 0.95, patience: 0.85, uncertainty_tolerance: 0.8, ethical_burden_tolerance: 0.7 },
    thrives: ["Detective workups", "Global health interest"],
    struggles: ["Need for high income"],
    downsides: ["Lowest pay in IM subspecialties"],
    dayInLife: "Consults, stewardship rounds, outpatient HIV clinic.",
    tags: ["cognitive"],
  },
  {
    id: "cardiology",
    name: "Cardiology",
    blurb: "Physiology + procedures; broad career arcs from imaging to interventional.",
    trainingYears: "3+3 yrs",
    incomeBand: 5, competitiveness: 4, lifestyle: 2, burnoutRisk: 4,
    emotionalBurden: 4, procedural: 4, patientInteraction: 4, callBurden: 4,
    emergencyFrequency: 4, physicalDemand: 2, familyFriendly: 2, autonomy: 4, prestige: 5,
    ideal: { analytical: 0.9, ambition: 0.85, competitiveness: 0.8, procedural: 0.6, income_priority: 0.85, stamina: 0.8 },
    thrives: ["Physiologic thinking + action"],
    struggles: ["Need for short training"],
    downsides: ["STEMI call", "Long fellowship"],
    dayInLife: "Clinic, echo, cath lab, consults.",
    tags: ["procedural", "cognitive"],
  },
  {
    id: "hemonc",
    name: "Hematology / Oncology",
    blurb: "Long relationships through serious illness.",
    trainingYears: "3+3 yrs",
    incomeBand: 4, competitiveness: 3, lifestyle: 3, burnoutRisk: 4,
    emotionalBurden: 5, procedural: 2, patientInteraction: 5, callBurden: 2,
    emergencyFrequency: 2, physicalDemand: 1, familyFriendly: 4, autonomy: 4, prestige: 4,
    ideal: { empathy: 0.9, ethical_burden_tolerance: 0.95, patience: 0.85, communication: 0.85, analytical: 0.85, death_comfort: 0.85 },
    thrives: ["Walking with patients long-term"],
    struggles: ["Discomfort with mortality"],
    downsides: ["Emotional toll"],
    dayInLife: "Clinic, infusion, tumor board.",
    tags: ["cognitive", "longitudinal"],
  },
  {
    id: "allergy_immunology",
    name: "Allergy / Immunology",
    blurb: "Outpatient, predictable, lifestyle-defining.",
    trainingYears: "3+2 yrs",
    incomeBand: 3, competitiveness: 3, lifestyle: 5, burnoutRisk: 1,
    emotionalBurden: 2, procedural: 2, patientInteraction: 4, callBurden: 1,
    emergencyFrequency: 1, physicalDemand: 1, familyFriendly: 5, autonomy: 5, prestige: 3,
    ideal: { lifestyle_balance: 0.95, family_priority: 0.9, patience: 0.7, analytical: 0.7, income_priority: 0.5 },
    thrives: ["Predictable hours", "Outpatient flow"],
    struggles: ["Need for acuity"],
    downsides: ["Narrow scope"],
    dayInLife: "9–4 clinic, weekends off.",
    tags: ["lifestyle"],
  },
  {
    id: "occupational_med",
    name: "Occupational Medicine",
    blurb: "Workplace health, public health intersection.",
    trainingYears: "3 yrs",
    incomeBand: 3, competitiveness: 1, lifestyle: 5, burnoutRisk: 1,
    emotionalBurden: 2, procedural: 1, patientInteraction: 3, callBurden: 1,
    emergencyFrequency: 1, physicalDemand: 1, familyFriendly: 5, autonomy: 5, prestige: 2,
    ideal: { lifestyle_balance: 0.95, family_priority: 0.9, analytical: 0.6 },
    thrives: ["Population health framing"],
    struggles: ["Need for hospital acuity"],
    downsides: ["Lower prestige"],
    dayInLife: "Clinic + corporate consulting, no call.",
    tags: ["lifestyle"],
  },
  {
    id: "rad_onc",
    name: "Radiation Oncology",
    blurb: "Physics-meets-medicine; high-stakes plans, controlled days.",
    trainingYears: "5 yrs",
    incomeBand: 5, competitiveness: 3, lifestyle: 5, burnoutRisk: 2,
    emotionalBurden: 4, procedural: 3, patientInteraction: 4, callBurden: 1,
    emergencyFrequency: 1, physicalDemand: 1, familyFriendly: 5, autonomy: 4, prestige: 4,
    ideal: { analytical: 0.9, perfectionism: 0.85, visual_spatial: 0.8, ethical_burden_tolerance: 0.85, lifestyle_balance: 0.85 },
    thrives: ["Physics + biology intersection"],
    struggles: ["Need for procedures"],
    downsides: ["Job market concerns"],
    dayInLife: "Contouring, on-treatment visits, planning.",
    tags: ["cognitive", "lifestyle"],
  },
  {
    id: "nicu",
    name: "Neonatology (NICU)",
    blurb: "Fragile newborns, high stakes, deep parental relationships.",
    trainingYears: "3+3 yrs",
    incomeBand: 4, competitiveness: 3, lifestyle: 2, burnoutRisk: 4,
    emotionalBurden: 5, procedural: 4, patientInteraction: 5, callBurden: 5,
    emergencyFrequency: 4, physicalDemand: 2, familyFriendly: 2, autonomy: 4, prestige: 4,
    ideal: { empathy: 0.9, stamina: 0.85, emotional_resilience: 0.95, focus_style: 0.6, ethical_burden_tolerance: 0.95 },
    thrives: ["Critical care + family work"],
    struggles: ["Sleep needs"],
    downsides: ["Night call", "Loss"],
    dayInLife: "Rounds, procedures, family meetings, nights.",
    tags: ["critical-care", "longitudinal"],
  },
  {
    id: "critical_care",
    name: "Critical Care",
    blurb: "The sickest patients, complex physiology, intense days.",
    trainingYears: "3+2 yrs",
    incomeBand: 4, competitiveness: 3, lifestyle: 2, burnoutRisk: 5,
    emotionalBurden: 5, procedural: 4, patientInteraction: 3, callBurden: 4,
    emergencyFrequency: 5, physicalDemand: 3, familyFriendly: 2, autonomy: 4, prestige: 4,
    ideal: { stamina: 0.95, emotional_resilience: 0.95, analytical: 0.9, procedural: 0.8, focus_style: 0.7, death_comfort: 0.95, lifestyle_balance: 0.2 },
    thrives: ["Multi-system physiology", "Shift-based intensity"],
    struggles: ["Discomfort with mortality conversations"],
    downsides: ["Moral distress", "Burnout"],
    dayInLife: "12h ICU shifts, procedures, family meetings.",
    tags: ["critical-care", "acute"],
  },
  {
    id: "gastroenterology",
    name: "Gastroenterology",
    blurb: "Scopes + cognitive medicine; lifestyle-friendly after fellowship.",
    trainingYears: "3+3 yrs",
    incomeBand: 5, competitiveness: 4, lifestyle: 4, burnoutRisk: 2,
    emotionalBurden: 2, procedural: 4, patientInteraction: 3, callBurden: 2,
    emergencyFrequency: 2, physicalDemand: 2, familyFriendly: 4, autonomy: 4, prestige: 4,
    ideal: { procedural: 0.7, visual_spatial: 0.7, analytical: 0.7, income_priority: 0.85, lifestyle_balance: 0.7 },
    thrives: ["Repetitive procedural mastery"],
    struggles: ["Aversion to scopes"],
    downsides: ["Long fellowship"],
    dayInLife: "Endo center mornings, clinic afternoons.",
    tags: ["procedural"],
  },
  {
    id: "urology",
    name: "Urology",
    blurb: "Surgical + medical; broad scope, decent lifestyle.",
    trainingYears: "5 yrs",
    incomeBand: 5, competitiveness: 4, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 3, procedural: 5, patientInteraction: 4, callBurden: 3,
    emergencyFrequency: 2, physicalDemand: 3, familyFriendly: 4, autonomy: 5, prestige: 4,
    ideal: { procedural: 0.85, visual_spatial: 0.8, communication: 0.7, income_priority: 0.8, lifestyle_balance: 0.65 },
    thrives: ["Robotic surgery", "Clinic + OR mix"],
    struggles: ["Aversion to procedures"],
    downsides: ["Heavy call early career"],
    dayInLife: "OR + clinic + endoscopic procedures.",
    tags: ["surgical"],
  },
  {
    id: "aerospace_med",
    name: "Aerospace Medicine",
    blurb: "Niche field, pilots/astronauts, public health overlap.",
    trainingYears: "3 yrs",
    incomeBand: 3, competitiveness: 1, lifestyle: 5, burnoutRisk: 1,
    emotionalBurden: 1, procedural: 1, patientInteraction: 3, callBurden: 1,
    emergencyFrequency: 1, physicalDemand: 2, familyFriendly: 5, autonomy: 5, prestige: 3,
    ideal: { lifestyle_balance: 0.95, analytical: 0.7, autonomy: 0.85 },
    thrives: ["Unusual environments", "Public health"],
    struggles: ["Hospital-loving folks"],
    downsides: ["Few jobs"],
    dayInLife: "Pilot evaluations, policy work, occasional clinic.",
    tags: ["niche", "lifestyle"],
  },
  {
    id: "geriatrics",
    name: "Geriatrics",
    blurb: "Complex elderly care, deep family work.",
    trainingYears: "3+1 yrs",
    incomeBand: 2, competitiveness: 1, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 4, procedural: 1, patientInteraction: 5, callBurden: 2,
    emergencyFrequency: 1, physicalDemand: 1, familyFriendly: 5, autonomy: 4, prestige: 2,
    ideal: { empathy: 0.95, patience: 0.95, ethical_burden_tolerance: 0.85, lifestyle_balance: 0.8, income_priority: 0.2 },
    thrives: ["Goals-of-care conversations"],
    struggles: ["Status-driven folks"],
    downsides: ["Low pay", "Heavy emotional weight"],
    dayInLife: "Home visits, nursing home rounds, clinic.",
    tags: ["longitudinal", "lifestyle"],
  },
  {
    id: "med_peds",
    name: "Med-Peds",
    blurb: "Combined IM + Peds; broadest possible primary care.",
    trainingYears: "4 yrs",
    incomeBand: 3, competitiveness: 2, lifestyle: 3, burnoutRisk: 3,
    emotionalBurden: 3, procedural: 1, patientInteraction: 5, callBurden: 3,
    emergencyFrequency: 2, physicalDemand: 2, familyFriendly: 4, autonomy: 3, prestige: 3,
    ideal: { empathy: 0.85, communication: 0.85, specialized_vs_broad: 0.15, patience: 0.8, chronic_vs_acute: 0.3 },
    thrives: ["Whole-family medicine", "Complex transitions of care"],
    struggles: ["Procedural-focused minds"],
    downsides: ["Longer training, modest pay"],
    dayInLife: "Mixed adult + peds clinics, hospital rotations.",
    tags: ["broad", "longitudinal"],
  },
  {
    id: "transplant_surgery",
    name: "Transplant Surgery",
    blurb: "Highest acuity surgery, brutal call, identity-defining.",
    trainingYears: "5+2 yrs",
    incomeBand: 5, competitiveness: 4, lifestyle: 1, burnoutRisk: 5,
    emotionalBurden: 5, procedural: 5, patientInteraction: 3, callBurden: 5,
    emergencyFrequency: 5, physicalDemand: 5, familyFriendly: 1, autonomy: 4, prestige: 5,
    ideal: { stamina: 1.0, perfectionism: 1.0, identity_career: 1.0, emotional_resilience: 0.95, death_comfort: 0.95, lifestyle_balance: 0.1, family_priority: 0.15 },
    thrives: ["Total devotion to craft"],
    struggles: ["Need for normal life"],
    downsides: ["No predictable schedule"],
    dayInLife: "Cases at any hour, ICU intensive.",
    tags: ["surgical", "high-acuity"],
  },
  {
    id: "omfs",
    name: "OMFS",
    blurb: "Combined dental + medical; surgical jaw & face.",
    trainingYears: "4–6 yrs",
    incomeBand: 5, competitiveness: 5, lifestyle: 4, burnoutRisk: 3,
    emotionalBurden: 3, procedural: 5, patientInteraction: 3, callBurden: 3,
    emergencyFrequency: 2, physicalDemand: 3, familyFriendly: 4, autonomy: 5, prestige: 4,
    ideal: { procedural: 0.95, visual_spatial: 0.9, perfectionism: 0.85, income_priority: 0.9, autonomy: 0.9 },
    thrives: ["Craft + entrepreneurship"],
    struggles: ["Aversion to long training"],
    downsides: ["Dual training pathway"],
    dayInLife: "OR + clinic mix.",
    tags: ["surgical", "procedural"],
  },
];
