/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialtiesRouteImport } from './routes/specialties'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'

const SpecialtiesRoute = SpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/compare': typeof CompareRoute
  '/methodology': typeof MethodologyRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/saved': typeof SavedRoute
  '/sources': typeof SourcesRoute
  '/specialties': typeof SpecialtiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/compare': typeof CompareRoute
  '/methodology': typeof MethodologyRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/saved': typeof SavedRoute
  '/sources': typeof SourcesRoute
  '/specialties': typeof SpecialtiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/compare': typeof CompareRoute
  '/methodology': typeof MethodologyRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/saved': typeof SavedRoute
  '/sources': typeof SourcesRoute
  '/specialties': typeof SpecialtiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/compare'
    | '/methodology'
    | '/onboarding'
    | '/results'
    | '/saved'
    | '/sources'
    | '/specialties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/compare'
    | '/methodology'
    | '/onboarding'
    | '/results'
    | '/saved'
    | '/sources'
    | '/specialties'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/compare'
    | '/methodology'
    | '/onboarding'
    | '/results'
    | '/saved'
    | '/sources'
    | '/specialties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  CompareRoute: typeof CompareRoute
  MethodologyRoute: typeof MethodologyRoute
  OnboardingRoute: typeof OnboardingRoute
  ResultsRoute: typeof ResultsRoute
  SavedRoute: typeof SavedRoute
  SourcesRoute: typeof SourcesRoute
  SpecialtiesRoute: typeof SpecialtiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialties': {
      id: '/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof SpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  CompareRoute: CompareRoute,
  MethodologyRoute: MethodologyRoute,
  OnboardingRoute: OnboardingRoute,
  ResultsRoute: ResultsRoute,
  SavedRoute: SavedRoute,
  SourcesRoute: SourcesRoute,
  SpecialtiesRoute: SpecialtiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
